## Generated by errnoparser (tools/errnoparser.py).
## DO NOT MODIFY!

const
  EPERM*: int32 = 1
  ENOENT*: int32 = 2
  ESRCH*: int32 = 3
  EINTR*: int32 = 4
  EIO*: int32 = 5
  ENXIO*: int32 = 6
  E2BIG*: int32 = 7
  ENOEXEC*: int32 = 8
  EBADF*: int32 = 9
  ECHILD*: int32 = 10
  EAGAIN*: int32 = 11
  ENOMEM*: int32 = 12
  EACCES*: int32 = 13
  EFAULT*: int32 = 14
  ENOTBLK*: int32 = 15
  EBUSY*: int32 = 16
  EEXIST*: int32 = 17
  EXDEV*: int32 = 18
  ENODEV*: int32 = 19
  ENOTDIR*: int32 = 20
  EISDIR*: int32 = 21
  EINVAL*: int32 = 22
  ENFILE*: int32 = 23
  EMFILE*: int32 = 24
  ENOTTY*: int32 = 25
  ETXTBSY*: int32 = 26
  EFBIG*: int32 = 27
  ENOSPC*: int32 = 28
  ESPIPE*: int32 = 29
  EROFS*: int32 = 30
  EMLINK*: int32 = 31
  EPIPE*: int32 = 32
  EDOM*: int32 = 33
  ERANGE*: int32 = 34
  EDEADLK*: int32 = 35
  ENAMETOOLONG*: int32 = 36
  ENOLCK*: int32 = 37
  ENOSYS*: int32 = 38
  ENOTEMPTY*: int32 = 39
  ELOOP*: int32 = 40
  EWOULDBLOCK*: int32 = 11
  ENOMSG*: int32 = 42
  EIDRM*: int32 = 43
  ECHRNG*: int32 = 44
  EL2NSYNC*: int32 = 45
  EL3HLT*: int32 = 46
  EL3RST*: int32 = 47
  ELNRNG*: int32 = 48
  EUNATCH*: int32 = 49
  ENOCSI*: int32 = 50
  EL2HLT*: int32 = 51
  EBADE*: int32 = 52
  EBADR*: int32 = 53
  EXFULL*: int32 = 54
  ENOANO*: int32 = 55
  EBADRQC*: int32 = 56
  EBADSLT*: int32 = 57
  EDEADLOCK*: int32 = 35
  EBFONT*: int32 = 59
  ENOSTR*: int32 = 60
  ENODATA*: int32 = 61
  ETIME*: int32 = 62
  ENOSR*: int32 = 63
  ENONET*: int32 = 64
  ENOPKG*: int32 = 65
  EREMOTE*: int32 = 66
  ENOLINK*: int32 = 67
  EADV*: int32 = 68
  ESRMNT*: int32 = 69
  ECOMM*: int32 = 70
  EPROTO*: int32 = 71
  EMULTIHOP*: int32 = 72
  EDOTDOT*: int32 = 73
  EBADMSG*: int32 = 74
  EOVERFLOW*: int32 = 75
  ENOTUNIQ*: int32 = 76
  EBADFD*: int32 = 77
  EREMCHG*: int32 = 78
  ELIBACC*: int32 = 79
  ELIBBAD*: int32 = 80
  ELIBSCN*: int32 = 81
  ELIBMAX*: int32 = 82
  ELIBEXEC*: int32 = 83
  EILSEQ*: int32 = 84
  ERESTART*: int32 = 85
  ESTRPIPE*: int32 = 86
  EUSERS*: int32 = 87
  ENOTSOCK*: int32 = 88
  EDESTADDRREQ*: int32 = 89
  EMSGSIZE*: int32 = 90
  EPROTOTYPE*: int32 = 91
  ENOPROTOOPT*: int32 = 92
  EPROTONOSUPPORT*: int32 = 93
  ESOCKTNOSUPPORT*: int32 = 94
  EOPNOTSUPP*: int32 = 95
  EPFNOSUPPORT*: int32 = 96
  EAFNOSUPPORT*: int32 = 97
  EADDRINUSE*: int32 = 98
  EADDRNOTAVAIL*: int32 = 99
  ENETDOWN*: int32 = 100
  ENETUNREACH*: int32 = 101
  ENETRESET*: int32 = 102
  ECONNABORTED*: int32 = 103
  ECONNRESET*: int32 = 104
  ENOBUFS*: int32 = 105
  EISCONN*: int32 = 106
  ENOTCONN*: int32 = 107
  ESHUTDOWN*: int32 = 108
  ETOOMANYREFS*: int32 = 109
  ETIMEDOUT*: int32 = 110
  ECONNREFUSED*: int32 = 111
  EHOSTDOWN*: int32 = 112
  EHOSTUNREACH*: int32 = 113
  EALREADY*: int32 = 114
  EINPROGRESS*: int32 = 115
  ESTALE*: int32 = 116
  EUCLEAN*: int32 = 117
  ENOTNAM*: int32 = 118
  ENAVAIL*: int32 = 119
  EISNAM*: int32 = 120
  EREMOTEIO*: int32 = 121
  EDQUOT*: int32 = 122
  ENOMEDIUM*: int32 = 123
  EMEDIUMTYPE*: int32 = 124
  ECANCELED*: int32 = 125
  ENOKEY*: int32 = 126
  EKEYEXPIRED*: int32 = 127
  EKEYREVOKED*: int32 = 128
  EKEYREJECTED*: int32 = 129
  EOWNERDEAD*: int32 = 130
  ENOTRECOVERABLE*: int32 = 131
  ERFKILL*: int32 = 132
  EHWPOISON*: int32 = 133
  ENOTSUP*: int32 = 95

const StringErrors* = [
  "Operation not permitted", ## EPERM (errno 1)
  "No such file or directory", ## ENOENT (errno 2)
  "No such process", ## ESRCH (errno 3)
  "Interrupted system call", ## EINTR (errno 4)
  "Input/output error", ## EIO (errno 5)
  "No such device or address", ## ENXIO (errno 6)
  "Argument list too long", ## E2BIG (errno 7)
  "Exec format error", ## ENOEXEC (errno 8)
  "Bad file descriptor", ## EBADF (errno 9)
  "No child processes", ## ECHILD (errno 10)
  "Resource temporarily unavailable", ## EAGAIN (errno 11)
  "Cannot allocate memory", ## ENOMEM (errno 12)
  "Permission denied", ## EACCES (errno 13)
  "Bad address", ## EFAULT (errno 14)
  "Block device required", ## ENOTBLK (errno 15)
  "Device or resource busy", ## EBUSY (errno 16)
  "File exists", ## EEXIST (errno 17)
  "Invalid cross-device link", ## EXDEV (errno 18)
  "No such device", ## ENODEV (errno 19)
  "Not a directory", ## ENOTDIR (errno 20)
  "Is a directory", ## EISDIR (errno 21)
  "Invalid argument", ## EINVAL (errno 22)
  "Too many open files in system", ## ENFILE (errno 23)
  "Too many open files", ## EMFILE (errno 24)
  "Inappropriate ioctl for device", ## ENOTTY (errno 25)
  "Text file busy", ## ETXTBSY (errno 26)
  "File too large", ## EFBIG (errno 27)
  "No space left on device", ## ENOSPC (errno 28)
  "Illegal seek", ## ESPIPE (errno 29)
  "Read-only file system", ## EROFS (errno 30)
  "Too many links", ## EMLINK (errno 31)
  "Broken pipe", ## EPIPE (errno 32)
  "Numerical argument out of domain", ## EDOM (errno 33)
  "Numerical result out of range", ## ERANGE (errno 34)
  "Resource deadlock avoided", ## EDEADLK (errno 35)
  "File name too long", ## ENAMETOOLONG (errno 36)
  "No locks available", ## ENOLCK (errno 37)
  "Function not implemented", ## ENOSYS (errno 38)
  "Directory not empty", ## ENOTEMPTY (errno 39)
  "Too many levels of symbolic links", ## ELOOP (errno 40)
  "Resource temporarily unavailable", ## EWOULDBLOCK (errno 11)
  "No message of desired type", ## ENOMSG (errno 42)
  "Identifier removed", ## EIDRM (errno 43)
  "Channel number out of range", ## ECHRNG (errno 44)
  "Level 2 not synchronized", ## EL2NSYNC (errno 45)
  "Level 3 halted", ## EL3HLT (errno 46)
  "Level 3 reset", ## EL3RST (errno 47)
  "Link number out of range", ## ELNRNG (errno 48)
  "Protocol driver not attached", ## EUNATCH (errno 49)
  "No CSI structure available", ## ENOCSI (errno 50)
  "Level 2 halted", ## EL2HLT (errno 51)
  "Invalid exchange", ## EBADE (errno 52)
  "Invalid request descriptor", ## EBADR (errno 53)
  "Exchange full", ## EXFULL (errno 54)
  "No anode", ## ENOANO (errno 55)
  "Invalid request code", ## EBADRQC (errno 56)
  "Invalid slot", ## EBADSLT (errno 57)
  "Resource deadlock avoided", ## EDEADLOCK (errno 35)
  "Bad font file format", ## EBFONT (errno 59)
  "Device not a stream", ## ENOSTR (errno 60)
  "No data available", ## ENODATA (errno 61)
  "Timer expired", ## ETIME (errno 62)
  "Out of streams resources", ## ENOSR (errno 63)
  "Machine is not on the network", ## ENONET (errno 64)
  "Package not installed", ## ENOPKG (errno 65)
  "Object is remote", ## EREMOTE (errno 66)
  "Link has been severed", ## ENOLINK (errno 67)
  "Advertise error", ## EADV (errno 68)
  "Srmount error", ## ESRMNT (errno 69)
  "Communication error on send", ## ECOMM (errno 70)
  "Protocol error", ## EPROTO (errno 71)
  "Multihop attempted", ## EMULTIHOP (errno 72)
  "RFS specific error", ## EDOTDOT (errno 73)
  "Bad message", ## EBADMSG (errno 74)
  "Value too large for defined data type", ## EOVERFLOW (errno 75)
  "Name not unique on network", ## ENOTUNIQ (errno 76)
  "File descriptor in bad state", ## EBADFD (errno 77)
  "Remote address changed", ## EREMCHG (errno 78)
  "Can not access a needed shared library", ## ELIBACC (errno 79)
  "Accessing a corrupted shared library", ## ELIBBAD (errno 80)
  ".lib section in a.out corrupted", ## ELIBSCN (errno 81)
  "Attempting to link in too many shared libraries", ## ELIBMAX (errno 82)
  "Cannot exec a shared library directly", ## ELIBEXEC (errno 83)
  "Invalid or incomplete multibyte or wide character", ## EILSEQ (errno 84)
  "Interrupted system call should be restarted", ## ERESTART (errno 85)
  "Streams pipe error", ## ESTRPIPE (errno 86)
  "Too many users", ## EUSERS (errno 87)
  "Socket operation on non-socket", ## ENOTSOCK (errno 88)
  "Destination address required", ## EDESTADDRREQ (errno 89)
  "Message too long", ## EMSGSIZE (errno 90)
  "Protocol wrong type for socket", ## EPROTOTYPE (errno 91)
  "Protocol not available", ## ENOPROTOOPT (errno 92)
  "Protocol not supported", ## EPROTONOSUPPORT (errno 93)
  "Socket type not supported", ## ESOCKTNOSUPPORT (errno 94)
  "Operation not supported", ## EOPNOTSUPP (errno 95)
  "Protocol family not supported", ## EPFNOSUPPORT (errno 96)
  "Address family not supported by protocol", ## EAFNOSUPPORT (errno 97)
  "Address already in use", ## EADDRINUSE (errno 98)
  "Cannot assign requested address", ## EADDRNOTAVAIL (errno 99)
  "Network is down", ## ENETDOWN (errno 100)
  "Network is unreachable", ## ENETUNREACH (errno 101)
  "Network dropped connection on reset", ## ENETRESET (errno 102)
  "Software caused connection abort", ## ECONNABORTED (errno 103)
  "Connection reset by peer", ## ECONNRESET (errno 104)
  "No buffer space available", ## ENOBUFS (errno 105)
  "Transport endpoint is already connected", ## EISCONN (errno 106)
  "Transport endpoint is not connected", ## ENOTCONN (errno 107)
  "Cannot send after transport endpoint shutdown", ## ESHUTDOWN (errno 108)
  "Too many references: cannot splice", ## ETOOMANYREFS (errno 109)
  "Connection timed out", ## ETIMEDOUT (errno 110)
  "Connection refused", ## ECONNREFUSED (errno 111)
  "Host is down", ## EHOSTDOWN (errno 112)
  "No route to host", ## EHOSTUNREACH (errno 113)
  "Operation already in progress", ## EALREADY (errno 114)
  "Operation now in progress", ## EINPROGRESS (errno 115)
  "Stale file handle", ## ESTALE (errno 116)
  "Structure needs cleaning", ## EUCLEAN (errno 117)
  "Not a XENIX named type file", ## ENOTNAM (errno 118)
  "No XENIX semaphores available", ## ENAVAIL (errno 119)
  "Is a named type file", ## EISNAM (errno 120)
  "Remote I/O error", ## EREMOTEIO (errno 121)
  "Disk quota exceeded", ## EDQUOT (errno 122)
  "No medium found", ## ENOMEDIUM (errno 123)
  "Wrong medium type", ## EMEDIUMTYPE (errno 124)
  "Operation canceled", ## ECANCELED (errno 125)
  "Required key not available", ## ENOKEY (errno 126)
  "Key has expired", ## EKEYEXPIRED (errno 127)
  "Key has been revoked", ## EKEYREVOKED (errno 128)
  "Key was rejected by service", ## EKEYREJECTED (errno 129)
  "Owner died", ## EOWNERDEAD (errno 130)
  "State not recoverable", ## ENOTRECOVERABLE (errno 131)
  "Operation not possible due to RF-kill", ## ERFKILL (errno 132)
  "Memory page has hardware error", ## EHWPOISON (errno 133)
  "Operation not supported", ## ENOTSUP (errno 95)
]
