#!/usr/bin/env python3
## Tool to parse `errno -l`'s output to generate a Nim mapping file
## Copyright (C) 2026 Trayambak Rai (xtrayambak@disroot.org)
import subprocess

res = subprocess.run(['errno', '-l'], capture_output = True, text = True).stdout

final = ""
preamble = "## Generated by errnoparser (tools/errnoparser.py).\n## DO NOT MODIFY!"
errors = "const"
string_errors = "const StringErrors* = ["

for line in res.split('\n'):
    splitted = line.split()
    if len(splitted) < 1:
        continue

    nam = splitted[0]
    errcode = int(splitted[1])
    emsg = ' '.join(splitted[2:len(splitted)])
    
    errors += f"\n  {nam}*: int32 = {errcode}"
    string_errors += f"\n  \"{emsg}\", ## {nam} (errno {errcode})"

string_errors += "\n]"

final += preamble
final += "\n\n"
final += errors
final += "\n\n"
final += string_errors

print(final)
