#!/usr/bin/env python3
## Tiny script to parse .tbl files from the kernel source
## and to emit Nim with them.
## Copyright (C) 2026 Trayambak Rai (xtrayambak@disroot.org)
import sys

buffer = "## Generated by tblparser (tools/tblparser.py) for " + sys.argv[1] + ".\n## DO NOT MODIFY!\n\ntype Syscall* = distinct uint64\n\nconst"
with open("tables/" + sys.argv[1] + ".tbl", "r") as table_file:
    contents = table_file.read()
    for line in contents.split('\n'):
        data = line.split()

        if len(data) < 1 or data[0] == '#': continue
        if data[1] == "x32": continue
        
        try:
            sc_num: int = int(data[0])
            sc_nam: str = data[2].lstrip('_')
            buffer += f"\n  SYS_{sc_nam}* = cast[Syscall]({sc_num})"
        except ValueError:
            continue

print(buffer)
